AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'misc/*'
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
