# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a11b20dba6593dbb0c3b6b4f051b1fbe45dda26df538ede57b98303ac544753a1bbfc0cb79f42ca50fdac5f08de111fd491e3eb3de1583753bec2a4c5e34327f

test:
  secret_key_base: 1bb5b26006ed59ac66514a44a2ebd363f8482214e9e1a114247fbc382e5d0d252247d2b9caf17c9d46abc14c5806ab15ab3f45c7555d8e6e0c83b904eca534f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
